# Generated by Django 3.1.7 on 2021-04-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
