# Generated by Django 3.1.7 on 2021-04-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_merge_20210412_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='save_post',
        ),
    ]
