# Generated by Django 3.1.7 on 2021-04-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_relation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='status',
            field=models.CharField(choices=[('a', 'accept'), ('r', 'reject')], default=None, max_length=30),
        ),
    ]
