# Generated by Django 3.1.7 on 2021-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210408_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'accept'), ('r', 'reject')], max_length=30),
        ),
    ]
