# Generated by Django 3.1.7 on 2021-04-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210412_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_full_name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
