# Generated by Django 3.1.7 on 2021-04-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210413_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='status',
        ),
    ]
