# Generated by Django 3.1.7 on 2021-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_relation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='_profile_following_+', through='accounts.Relation', to='accounts.Profile'),
        ),
    ]
